"""Agent Bridge — 将审查结果转换为 AI 编码 Agent 可直接消费的 Prompt

支持三种输出模式:
  1. codebuddy   — CodeBuddy 任务格式
  2. cursor      — Cursor Chat 格式
  3. universal   — 通用结构化 Markdown（默认，任何 LLM/Agent 可用）

用法:
  bridge = AgentBridge()
  prompt = bridge.build_prompt(merged_findings, target_files, mode="codebuddy")
  bridge.emit(prompt, output="stdout")   # 直接输出到终端
  bridge.emit(prompt, output="file")     # 保存到 .codefalcon/agent_prompt.md
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from src.orchestrator.state import Finding, ReviewState
from src.utils.cost_tracker import CostTracker

logger = logging.getLogger(__name__)


class AgentBridge:
    """审查结果 → Agent Prompt 转换器"""

    AGENT_OUTPUT_DIR = ".codefalcon"
    PROMPT_FILENAME = "agent_prompt.md"

    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = Path(output_dir or self.AGENT_OUTPUT_DIR)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    # ---- 公共 API ----

    def build_prompt(
        self,
        findings: list,
        target_files: dict[str, str],
        mode: str = "codebuddy",
        spec_content: str = "",
    ) -> str:
        """将审查结果转换为 Agent 可消费的 Prompt

        Args:
            findings: merged_findings 列表 (dict 或 Finding 对象)
            target_files: {filepath: content} 字典
            mode: 输出格式 — "codebuddy" | "cursor" | "universal"
            spec_content: 可选的项目规范内容
        """
        findings = self._normalize(findings)
        if not findings:
            return self._build_clean_prompt(mode)

        if mode == "codebuddy":
            return self._build_codebuddy_prompt(findings, target_files, spec_content)
        elif mode == "cursor":
            return self._build_cursor_prompt(findings, target_files, spec_content)
        else:
            return self._build_universal_prompt(findings, target_files, spec_content)

    def emit(
        self,
        prompt: str,
        output: str = "file",
        filepath: Optional[str] = None,
    ) -> str:
        """输出 Agent Prompt

        Args:
            prompt: build_prompt 生成的 Prompt 文本
            output: "stdout" | "file" | "both"
            filepath: 自定义文件路径（默认 .codefalcon/agent_prompt.md）

        Returns:
            输出文件路径（file 模式）或 prompt 文本（stdout 模式）
        """
        if output in ("file", "both"):
            dest = Path(filepath or self.output_dir / self.PROMPT_FILENAME)
            dest.write_text(prompt, encoding="utf-8")
            logger.info(f"[AgentBridge] Prompt 已保存到 {dest}")

        if output in ("stdout", "both"):
            print(prompt)

        return str(self.output_dir / self.PROMPT_FILENAME)

    def build_from_state(
        self,
        state: dict,
        mode: str = "codebuddy",
    ) -> str:
        """从 ReviewState(dict) 直接构建 Prompt（便捷方法）"""
        findings = state.get("merged_findings", [])
        target_files = state.get("target_files", {})
        spec = state.get("spec_content", "")
        return self.build_prompt(findings, target_files, mode, spec)

    def build_from_report(self, report_path: str, mode: str = "codebuddy") -> Optional[str]:
        """从历史 JSON 报告重建 Agent Prompt"""
        try:
            data = json.loads(Path(report_path).read_text(encoding="utf-8"))
            findings = data.get("findings", [])
            # 历史报告没有原始文件内容，用空字典
            return self.build_prompt(findings, {}, mode)
        except (json.JSONDecodeError, FileNotFoundError) as e:
            logger.error(f"[AgentBridge] 读取报告失败: {e}")
            return None

    # ---- 内部：格式构建器 ----

    def _build_codebuddy_prompt(
        self, findings: list[dict], target_files: dict, spec: str = ""
    ) -> str:
        """CodeBuddy 格式：任务式 Prompt，引导 Agent 逐项修复"""
        sev = self._severity_stats(findings)
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        lines = [
            "# Code Review — Automatic Fix Request",
            f"",
            f"> Generated by CodeFalcon at {now}",
            f"> Issues: {len(findings)} total ({sev['error']} errors, {sev['warning']} warnings, {sev['info']} info)",
            f"",
            f"## Task",
            f"",
            f"Please review and fix the following issues found in the codebase. "
            f"For each issue, first read the relevant file, then apply the suggested fix.",
            f"",
            f"## Issues to Fix (sorted by severity)",
            f"",
        ]

        # 按严重度分组
        for severity in ("error", "warning", "info"):
            group = [f for f in findings if f["severity"] == severity]
            if not group:
                continue
            emoji = {"error": "🔴", "warning": "🟡", "info": "🔵"}[severity]
            lines.append(f"### {emoji} {severity.upper()} ({len(group)})")
            lines.append("")

            for i, f in enumerate(group, 1):
                file_path = f["file_path"]
                lines.append(f"**{i}. [{f['category'].upper()}] `{file_path}:{f['line']}`**")
                lines.append(f"> {f['message']}")
                if f.get("suggestion"):
                    lines.append(f"")
                    lines.append(f"**Fix**: {f['suggestion']}")

                # 附上相关代码片段
                if file_path in target_files:
                    snippet = self._extract_snippet(target_files[file_path], f["line"])
                    if snippet.strip():
                        lines.append(f"")
                        lines.append(f"```python")
                        lines.append(snippet.rstrip())
                        lines.append(f"```")
                lines.append("")

        # 添加操作指引
        lines.extend([
            f"---",
            f"",
            f"## Instructions for the Agent",
            f"",
            f"1. Read each file listed above",
            f"2. Apply the suggested fixes **one issue at a time**",
            f"3. After fixing all ERROR-level issues, re-run codefalcon review to verify",
            f"4. Only fix WARNING/INFO issues after errors are resolved",
            f"",
            f"**Priority**: Fix security issues (SEC-xxx) and bugs FIRST, then architecture, then style.",
        ])

        if spec:
            lines.extend([
                f"",
                f"## Project Spec (for reference)",
                f"",
                f"Make sure fixes comply with the project spec:",
                f"",
                f"```markdown",
                spec[:2000],
                f"```",
            ])

        return "\n".join(lines)

    def _build_cursor_prompt(
        self, findings: list[dict], target_files: dict, spec: str = ""
    ) -> str:
        """Cursor 格式：Chat 式对话 Prompt"""
        sev = self._severity_stats(findings)
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        lines = [
            f"I just ran a code review and found {len(findings)} issues "
            f"({sev['error']} errors, {sev['warning']} warnings). "
            f"Can you help me fix them?",
            f"",
            f"Here are the issues:",
            f"",
        ]

        for i, f in enumerate(findings, 1):
            file_path = f["file_path"]
            sev_char = {"error": "❌", "warning": "⚠️", "info": "ℹ️"}[f["severity"]]
            lines.append(f"{i}. {sev_char} `{file_path}:{f['line']}` — {f['message']}")
            if f.get("suggestion"):
                lines.append(f"   → {f['suggestion']}")

        lines.extend([
            f"",
            f"Please fix these issues. Start with the errors (marked ❌), "
            f"then the warnings (⚠️), and finally the info items (ℹ️).",
        ])

        # 附上所有目标文件内容
        if target_files:
            lines.append(f"")
            lines.append(f"Here are the relevant files:")
            for fp, content in target_files.items():
                lines.append(f"")
                lines.append(f"### {fp}")
                lines.append(f"```python")
                lines.append(content.rstrip())
                lines.append(f"```")

        return "\n".join(lines)

    def _build_universal_prompt(
        self, findings: list[dict], target_files: dict, spec: str = ""
    ) -> str:
        """通用格式：结构化 Markdown，任何 LLM/Agent 可消费"""
        sev = self._severity_stats(findings)
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        lines = [
            f"# CodeFalcon Review — Agent Fix Request",
            f"",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Review Time | {now} |",
            f"| Total Issues | {len(findings)} |",
            f"| Errors | {sev['error']} |",
            f"| Warnings | {sev['warning']} |",
            f"| Info | {sev['info']} |",
            f"",
            f"---",
            f"",
            f"## Action Items",
            f"",
        ]

        for i, f in enumerate(findings, 1):
            sev_tag = f["severity"].upper()
            cat = f["category"]
            file_path = f["file_path"]
            line = f["line"]

            lines.append(f"### Fix #{i}: [{sev_tag}] [{cat}] `{file_path}:{line}`")
            lines.append(f"")
            lines.append(f"**Problem**: {f['message']}")
            lines.append(f"**Action**: {f.get('suggestion', 'N/A')}")
            lines.append(f"**Source**: {f.get('agent_source', 'unknown')}")
            lines.append(f"")

        # 成本信息
        cost = CostTracker().get_summary()
        if cost["total_tokens"] > 0:
            lines.extend([
                f"---",
                f"",
                f"## Review Cost",
                f"",
                f"- Tokens: {cost['total_tokens']} (in: {cost['total_input_tokens']}, out: {cost['total_output_tokens']})",
                f"- Estimated cost: ${cost['estimated_cost_usd']:.6f}",
                f"",
            ])

        return "\n".join(lines)

    def _build_clean_prompt(self, mode: str) -> str:
        """无问题时的提示"""
        return (
            "# CodeFalcon Review — No Issues Found\n\n"
            "✅ Code review completed. No bugs, security issues, or style violations detected.\n\n"
            "The code is ready to proceed."
        )

    # ---- 工具方法 ----

    def _normalize(self, findings: list) -> list[dict]:
        """将 Finding 对象或 dict 统一转为 dict（兼容 file/file_path, source/agent_source）"""
        result = []
        for f in findings:
            if isinstance(f, dict):
                result.append({
                    "severity": f.get("severity", "info"),
                    "category": f.get("category", "unknown"),
                    "file_path": f.get("file_path", f.get("file", "")),
                    "line": f.get("line", 0),
                    "message": f.get("message", ""),
                    "suggestion": f.get("suggestion", ""),
                    "agent_source": f.get("agent_source", f.get("source", "")),
                })
            else:
                result.append({
                    "severity": getattr(f, "severity", "info"),
                    "category": getattr(f, "category", "unknown"),
                    "file_path": getattr(f, "file_path", ""),
                    "line": getattr(f, "line", 0),
                    "message": getattr(f, "message", ""),
                    "suggestion": getattr(f, "suggestion", ""),
                    "agent_source": getattr(f, "agent_source", ""),
                })
        return result

    def _severity_stats(self, findings: list[dict]) -> dict:
        """统计各严重度数量"""
        stats = {"error": 0, "warning": 0, "info": 0}
        for f in findings:
            sev = f.get("severity", "info")
            if sev in stats:
                stats[sev] += 1
        return stats

    def _extract_snippet(self, content: str, target_line: int, context: int = 3) -> str:
        """提取代码片段（目标行 ± 上下文）"""
        lines = content.split("\n")
        if target_line <= 0 or target_line > len(lines):
            return ""

        start = max(0, target_line - context - 1)
        end = min(len(lines), target_line + context)
        return "\n".join(lines[start:end])
